Repository omise/omise-android, pull requests merged in 2019-09, with the labels that each got.

#78 Upgraded Gradle wrapper to version 5.6.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement, v3.0

#79 Fix base class serialization
  sdk/src/androidTest/java/co/omise/android/models/ModelTest.kt
  sdk/src/main/java/co/omise/android/models/Capability.kt
  sdk/src/main/java/co/omise/android/models/Card.kt
  sdk/src/main/java/co/omise/android/models/Model.kt
  sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
  sdk/src/main/java/co/omise/android/models/References.kt
  sdk/src/main/java/co/omise/android/models/Source.kt
  sdk/src/main/java/co/omise/android/models/Token.kt
  sdk/src/test/java/co/omise/android/ParcelableTest.kt
  sdk/src/test/resources/data/objects/capability_object.json
  sdk/src/test/resources/data/objects/payment_method_object.json
Labels: bug, v3.0

#84 Updated card's RegEx.
  sdk/src/main/java/co/omise/android/models/CardBrand.java
Labels: enhancement

#85 Set Omise-Version onto the request header.
  sdk/src/main/java/co/omise/android/Client.java
  sdk/src/main/java/co/omise/android/models/Model.java
Labels: enhancement

#83 Create payment from credit card
  app/src/main/java/co/omise/android/example/CheckoutActivity.java
  app/src/main/java/co/omise/android/example/MainActivity.java
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
  sdk/src/main/java/co/omise/android/ui/OmiseActivity.kt
  sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
  sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/PaymentCreatorActivityTest.kt
Labels: enhancement, v3.0

#87 Create payment from installment
  sdk/src/main/java/co/omise/android/models/SourceType.kt
  sdk/src/main/java/co/omise/android/ui/InstallmentChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/InternetBankingChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/OmiseFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
  sdk/src/main/res/values/strings.xml
  sdk/src/sharedTest/java/co/omise/android/ui/InstallmentChooserFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/InstallmentTermChooserFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/TestFragmentActivity.kt
Labels: enhancement, v3.0

#88 Create payment from EContext
  sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
  sdk/src/main/java/co/omise/android/models/SourceType.kt
  sdk/src/main/java/co/omise/android/ui/EContextFormFragment.kt
  sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/InternetBankingChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/OmiseFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
  sdk/src/main/res/layout/fragment_econtext_form.xml
  sdk/src/main/res/values/dimens.xml
  sdk/src/main/res/values/strings.xml
  sdk/src/sharedTest/java/co/omise/android/ui/EContextFormFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/InstallmentChooserFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/utils/ViewUtils.kt
Labels: enhancement, v3.0

#90 Added ItemDecoration to RecyclerView.
  sdk/src/main/java/co/omise/android/ui/OmiseListFragment.kt
Labels: enhancement, v3.0

#89 Create payment from Alipay / Bill payment Tesco Lotus
  sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
  sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/EContextFormFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
  sdk/src/test/resources/robolectric.properties
Labels: enhancement, v3.0

#92 Delete sdk/AndroidManifest.xml from debug mode
  sdk/src/androidTest/AndroidManifest.xml
  sdk/src/debug/res/values/strings.xml
  sdk/src/sharedTest/AndroidManifest.xml
Labels: enhancement, v3.0

#91 Payment creator handle error messages
  sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt
  sdk/src/main/java/co/omise/android/models/Amount.kt
  sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
  sdk/src/main/res/values-ja/strings.xml
  sdk/src/main/res/values-th/strings.xml
  sdk/src/main/res/values/strings.xml
  sdk/src/test/java/co/omise/android/extensions/APIErrorExtensionsTest.kt
Labels: enhancement, v3.0

#93 Update Circle ci config
  .circleci/config.yml
  sdk/src/test/java/co/omise/android/CardModelTest.java
Labels: enhancement

#94 Update the sample app to new design
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/omise/android/example/BaseActivity.java
  app/src/main/java/co/omise/android/example/CheckoutActivity.java
  app/src/main/java/co/omise/android/example/MainActivity.java
  app/src/main/java/co/omise/android/example/Product.java
  app/src/main/java/co/omise/android/example/ProductListAdapter.java
  app/src/main/java/co/omise/android/example/ProductRepository.java
  app/src/main/java/co/omise/android/example/ReceiptActivity.java
  app/src/main/res/drawable-hdpi/shoes.png
  app/src/main/res/drawable-mdpi/shoes.png
  app/src/main/res/drawable-xhdpi/shoes.png
  app/src/main/res/drawable-xxhdpi/shoes.png
  app/src/main/res/drawable-xxxhdpi/shoes.png
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/layout/activity_checkout.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_receipt.xml
  app/src/main/res/layout/list_item_product.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
  sdk/src/main/java/co/omise/android/models/Amount.kt
Labels: enhancement, v3.0

#95 Payment setting page
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/omise/android/example/CheckoutActivity.java
  app/src/main/java/co/omise/android/example/PaymentSetting.kt
  app/src/main/java/co/omise/android/example/PaymentSettingActivity.kt
  app/src/main/java/co/omise/android/example/PaymentSettingFragment.kt
  app/src/main/res/layout/activity_payment_setting.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference_payment_setting.xml
  build.gradle
  sdk/build.gradle
  sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
Labels: enhancement, v3.0

#97 Sample app in Kotlin
  app/build.gradle
  app/src/java/java/co/omise/android/example/CheckoutActivity.java
  app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/omise/android/example/PaymentSettingActivity.kt
  app/src/main/java/co/omise/android/example/PaymentSettingFragment.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, v3.0
