Repository omise/omise-android, pull requests merged in 2019-07, with the labels that each got.

#55 Update project
  .idea/misc.xml
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  sdk/build.gradle
Labels: enhancement

#56 Split authorizing payment url verifier
  app/src/main/java/co/omise/android/example/MainActivity.java
  gradle.properties
  sdk/build.gradle
  sdk/src/androidTest/java/co/omise/android/models/ModelTest.java
  sdk/src/main/java/co/omise/android/AuthorizingPaymentURLVerifier.kt
  sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.java
  sdk/src/sharedTest/java/co/omise/android/AuthorizingPaymentURLVerifierTest.kt
  sdk/src/sharedTest/java/co/omise/android/CreditCardEditTextTest.java
Labels: enhancement

#57 Refactor request flow
  .idea/misc.xml
  README.md
  sdk/src/main/java/co/omise/android/Client.java
  sdk/src/main/java/co/omise/android/Invocation.java
  sdk/src/main/java/co/omise/android/TokenRequest.java
  sdk/src/main/java/co/omise/android/TokenRequestListener.java
  sdk/src/main/java/co/omise/android/api/Client.kt
  sdk/src/main/java/co/omise/android/api/Invocation.kt
  sdk/src/main/java/co/omise/android/api/Request.kt
  sdk/src/main/java/co/omise/android/api/RequestBuilder.kt
  sdk/src/main/java/co/omise/android/api/RequestListener.kt
  sdk/src/main/java/co/omise/android/api/TLSPatch.java
  sdk/src/main/java/co/omise/android/api/exceptions/IllegalModelException.kt
  sdk/src/main/java/co/omise/android/api/exceptions/RedirectionException.kt
  sdk/src/main/java/co/omise/android/models/ModelParserUtil.kt
  sdk/src/main/java/co/omise/android/models/Token.java
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.java
Labels: enhancement, v3.0

#58 Adopt AndroidX to AuthorizingPaymentActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/omise/android/example/MainActivity.java
  build.gradle
  sdk/build.gradle
  sdk/src/debug/AndroidManifest.xml
  sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.java
  sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
  sdk/src/main/res/values/styles.xml
  sdk/src/sharedTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt
Labels: enhancement, v3.0

#59 Capabilities api request
  sdk/src/main/java/co/omise/android/api/Client.kt
  sdk/src/main/java/co/omise/android/api/Config.kt
  sdk/src/main/java/co/omise/android/api/Configurer.kt
  sdk/src/main/java/co/omise/android/api/EndPoint.kt
  sdk/src/main/java/co/omise/android/api/RequestBuilder.kt
  sdk/src/main/java/co/omise/android/api/exceptions/ClientException.kt
  sdk/src/main/java/co/omise/android/models/Capability.kt
  sdk/src/main/java/co/omise/android/models/JSON.java
  sdk/src/main/java/co/omise/android/models/ModelParserUtil.kt
  sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
  sdk/src/main/java/co/omise/android/models/Token.java
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.java
Labels: enhancement, v3.0

#61 Fix spinner default view
  sdk/src/main/java/co/omise/android/ui/NumberRangeSpinnerAdapter.java
  sdk/src/main/res/layout/activity_credit_card.xml
Labels: bug

#63 Release version 2.6.6
  CHANGELOG.md
  README.md
  sdk/build.gradle
Labels: release

#64 Jackson integration
  app/src/main/java/co/omise/android/example/ReceiptActivity.java
  sdk/build.gradle
  sdk/src/androidTest/java/co/omise/android/models/ModelTest.java
  sdk/src/main/java/co/omise/android/api/Config.kt
  sdk/src/main/java/co/omise/android/api/Configurer.kt
  sdk/src/main/java/co/omise/android/api/EndPoint.kt
  sdk/src/main/java/co/omise/android/api/Invocation.kt
  sdk/src/main/java/co/omise/android/api/exceptions/IllegalModelException.kt
  sdk/src/main/java/co/omise/android/models/APIError.java
  sdk/src/main/java/co/omise/android/models/APIError.kt
  sdk/src/main/java/co/omise/android/models/Capability.kt
  sdk/src/main/java/co/omise/android/models/Card.java
  sdk/src/main/java/co/omise/android/models/Card.kt
  sdk/src/main/java/co/omise/android/models/CardBrand.java
  sdk/src/main/java/co/omise/android/models/CardBrand.kt
  sdk/src/main/java/co/omise/android/models/JSON.java
  sdk/src/main/java/co/omise/android/models/Model.java
  sdk/src/main/java/co/omise/android/models/Model.kt
  sdk/src/main/java/co/omise/android/models/ModelParserUtil.kt
  sdk/src/main/java/co/omise/android/models/ModelTypeResolver.kt
  sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
  sdk/src/main/java/co/omise/android/models/Serializer.kt
  sdk/src/main/java/co/omise/android/models/Token.java
  sdk/src/main/java/co/omise/android/models/Token.kt
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
  sdk/src/test/java/co/omise/android/CardModelTest.java
  sdk/src/test/java/co/omise/android/ConfigTest.java
  sdk/src/test/java/co/omise/android/ConfigurerTest.java
  sdk/src/test/java/co/omise/android/EndpointTest.java
  sdk/src/test/java/co/omise/android/OmiseTest.java
  sdk/src/test/java/co/omise/android/SerializationTest.java
  sdk/src/test/resources/data/objects/capability_object.json
  sdk/src/test/resources/data/objects/card_object.json
  sdk/src/test/resources/data/objects/payment_method_object.json
  sdk/src/test/resources/data/objects/token_object.json
Labels: enhancement, v3.0
