Repository omise/omise-android, pull requests merged in 2019-08, with the labels that each got.

#65 Revise credit card error messages
  sdk/build.gradle
  sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt
  sdk/src/main/java/co/omise/android/extensions/StringExtensions.kt
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
  sdk/src/main/java/co/omise/android/ui/OmiseEditText.kt
  sdk/src/main/res/layout/activity_credit_card.xml
  sdk/src/main/res/values-ja/strings.xml
  sdk/src/main/res/values-th/strings.xml
  sdk/src/main/res/values/colors.xml
  sdk/src/main/res/values/dimen.xml
  sdk/src/main/res/values/ids.xml
  sdk/src/main/res/values/strings.xml
  sdk/src/main/res/values/styles.xml
  sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
  sdk/src/test/java/co/omise/android/extensions/APIErrorExtensionsTest.kt
  sdk/src/test/java/co/omise/android/ui/OmiseEditTextTest.kt
  sdk/src/test/resources/data/objects/error_object.json
Labels: enhancement, v3.0

#67 Sources api request
  app/build.gradle
  sdk/build.gradle
  sdk/src/main/java/co/omise/android/api/RequestBuilder.kt
  sdk/src/main/java/co/omise/android/models/FlowType.kt
  sdk/src/main/java/co/omise/android/models/Model.kt
  sdk/src/main/java/co/omise/android/models/ModelTypeResolver.kt
  sdk/src/main/java/co/omise/android/models/References.kt
  sdk/src/main/java/co/omise/android/models/Serializer.kt
  sdk/src/main/java/co/omise/android/models/Source.kt
  sdk/src/main/java/co/omise/android/models/SourceType.kt
  sdk/src/test/resources/data/objects/source_object.json
Labels: enhancement, v3.0

#68 Changed Token request body serialization
  sdk/src/main/java/co/omise/android/models/CardParam.kt
  sdk/src/main/java/co/omise/android/models/Token.kt
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
Labels: enhancement, v3.0

#69 Theming credit card form
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/color/button_text_color.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
  sdk/src/main/java/co/omise/android/ui/CreditCardEditText.kt
  sdk/src/main/java/co/omise/android/ui/OmiseEditText.kt
  sdk/src/main/res/drawable/bg_button.xml
  sdk/src/main/res/drawable/bg_edit_text_outlined.xml
  sdk/src/main/res/layout/activity_credit_card.xml
  sdk/src/main/res/values-ja/strings.xml
  sdk/src/main/res/values-th/strings.xml
  sdk/src/main/res/values/attrs.xml
  sdk/src/main/res/values/colors.xml
  sdk/src/main/res/values/dimens.xml
  sdk/src/main/res/values/strings.xml
  sdk/src/main/res/values/styles.xml
  sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
  sdk/src/test/java/co/omise/android/ui/CreditCardEditTextTest.kt
Labels: enhancement, v3.0

#70 Remove certificate pinning
  sdk/src/main/java/co/omise/android/Client.java
Labels: enhancement

#71 Simplify Gradle file
  app/build.gradle
  build.gradle
  sdk/build.gradle
Labels: enhancement, v3.0

#72 Upgrade Android Studio 3.5
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, v3.0

#73 Circle ci integration
  .circleci/config.yml
Labels: enhancement, v3.0

#74 Integrate Parcelize in the project
  sdk/build.gradle
  sdk/src/main/java/co/omise/android/models/Capability.kt
  sdk/src/main/java/co/omise/android/models/Card.kt
  sdk/src/main/java/co/omise/android/models/CardBrand.kt
  sdk/src/main/java/co/omise/android/models/FlowType.kt
  sdk/src/main/java/co/omise/android/models/Model.kt
  sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
  sdk/src/main/java/co/omise/android/models/References.kt
  sdk/src/main/java/co/omise/android/models/Source.kt
  sdk/src/main/java/co/omise/android/models/SourceType.kt
  sdk/src/main/java/co/omise/android/models/Token.kt
  sdk/src/test/java/co/omise/android/ParcelableTest.kt
Labels: enhancement, v3.0

#75 Fix serialization test
  sdk/src/main/java/co/omise/android/models/FlowType.kt
  sdk/src/test/java/co/omise/android/SerializationTest.java
Labels: bug, v3.0

#76 Model immutability
  sdk/src/main/java/co/omise/android/models/Capability.kt
  sdk/src/main/java/co/omise/android/models/Card.kt
  sdk/src/main/java/co/omise/android/models/Model.kt
  sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
  sdk/src/main/java/co/omise/android/models/References.kt
  sdk/src/main/java/co/omise/android/models/Source.kt
  sdk/src/main/java/co/omise/android/models/Token.kt
  sdk/src/test/java/co/omise/android/ParcelableTest.kt
Labels: enhancement, v3.0

#77 Fix deserialize source response
  sdk/src/main/java/co/omise/android/models/FlowType.kt
  sdk/src/main/java/co/omise/android/models/Source.kt
  sdk/src/main/java/co/omise/android/models/SourceType.kt
Labels: bug, v3.0
