Repository omise/omise-android, pull requests merged in 2019-10, with the labels that each got.

#98 Translate payment creator
  sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt
  sdk/src/main/java/co/omise/android/ui/EContextFormFragment.kt
  sdk/src/main/java/co/omise/android/ui/InstallmentChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/InternetBankingChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/OmiseListFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
  sdk/src/main/res/layout/fragment_econtext_form.xml
  sdk/src/main/res/values-ja/strings.xml
  sdk/src/main/res/values-th/strings.xml
  sdk/src/main/res/values/strings.xml
Labels: enhancement, v3.0

#99 Update Japan translation.
  sdk/src/main/res/values-ja/strings.xml
Labels: enhancement, v3.0

#100 Update sample app's layout to support small screen
  app/src/main/res/layout/activity_checkout.xml
Labels: bug, v3.0

#102 Fix tests
  .circleci/config.yml
  build.gradle
  gradle.properties
  sdk/build.gradle
  sdk/src/androidTest/java/co/omise/android/ui/CreditCardActivityInstrumentedTest.kt
  sdk/src/androidTest/java/co/omise/android/ui/SecurityCodeTooltipDialogFragmentInstrumentedTest.kt
  sdk/src/main/AndroidManifest.xml
  sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
  sdk/src/main/java/co/omise/android/ui/SecurityCodeTooltipDialogFragment.kt
  sdk/src/sharedTest/java/co/omise/android/AuthorizingPaymentURLVerifierTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/EContextFormFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/InstallmentTermChooserFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/PaymentCreatorActivityTest.kt
  sdk/src/sharedTest/java/co/omise/android/ui/SecurityCodeTooltipDialogFragmentTest.kt
  sdk/src/sharedTest/java/co/omise/android/utils/ViewUtils.kt
  sdk/src/test/java/co/omise/android/ui/CreditCardActivityExceptionTest.kt
  sdk/src/test/java/co/omise/android/ui/PaymentCreatorActivityExceptionTest.kt
  settings.gradle
  testsupport/.gitignore
  testsupport/build.gradle
  testsupport/consumer-rules.pro
  testsupport/proguard-rules.pro
  testsupport/src/main/AndroidManifest.xml
Labels: bug, v3.0

#103 Droped support Laser debit card.
  sdk/src/main/java/co/omise/android/models/CardBrand.kt
Labels: enhancement, v3.0

#105 Downgrade OkHttp to version 3
  build.gradle
  sdk/src/main/java/co/omise/android/api/Configurer.kt
  sdk/src/main/java/co/omise/android/api/Invocation.kt
  sdk/src/main/java/co/omise/android/api/RequestBuilder.kt
Labels: bug, v3.0

#101 Added 'points' source type.
  sdk/src/main/java/co/omise/android/models/SourceType.kt
  sdk/src/main/java/co/omise/android/ui/EContextFormFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
  sdk/src/sharedTest/java/co/omise/android/ui/EContextFormFragmentTest.kt
Labels: enhancement, v3.0

#107 Upgraded Android Studio 3.5.1
  build.gradle
Labels: enhancement

#108 Textual changes
  app/src/main/res/values/strings.xml
  sdk/src/androidTest/java/co/omise/android/ui/CreditCardActivityInstrumentedTest.kt
  sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
  sdk/src/main/res/layout/activity_credit_card.xml
  sdk/src/main/res/values-ja/strings.xml
  sdk/src/main/res/values-th/strings.xml
  sdk/src/main/res/values/strings.xml
  sdk/src/test/java/co/omise/android/extensions/APIErrorExtensionsTest.kt
Labels: enhancement, v3.0

#109 Code documentation
  sdk/src/main/java/co/omise/android/AuthorizingPaymentURLVerifier.kt
  sdk/src/main/java/co/omise/android/CardNumber.java
  sdk/src/main/java/co/omise/android/SDKLog.java
  sdk/src/main/java/co/omise/android/api/Client.kt
  sdk/src/main/java/co/omise/android/api/Config.kt
  sdk/src/main/java/co/omise/android/api/Configurer.kt
  sdk/src/main/java/co/omise/android/api/EndPoint.kt
  sdk/src/main/java/co/omise/android/api/Invocation.kt
  sdk/src/main/java/co/omise/android/api/Request.kt
  sdk/src/main/java/co/omise/android/api/RequestBuilder.kt
  sdk/src/main/java/co/omise/android/api/exceptions/ClientException.kt
  sdk/src/main/java/co/omise/android/api/exceptions/RedirectionException.kt
  sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt
  sdk/src/main/java/co/omise/android/extensions/StringExtensions.kt
  sdk/src/main/java/co/omise/android/extensions/ViewExtensions.kt
  sdk/src/main/java/co/omise/android/models/APIError.kt
  sdk/src/main/java/co/omise/android/models/Amount.kt
  sdk/src/main/java/co/omise/android/models/CardBrand.kt
  sdk/src/main/java/co/omise/android/models/CardParam.kt
  sdk/src/main/java/co/omise/android/models/Model.kt
  sdk/src/main/java/co/omise/android/models/ModelTypeResolver.kt
  sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
  sdk/src/main/java/co/omise/android/models/Serializer.kt
  sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
  sdk/src/main/java/co/omise/android/ui/CardNameEditText.kt
  sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
  sdk/src/main/java/co/omise/android/ui/CreditCardEditText.kt
  sdk/src/main/java/co/omise/android/ui/EContextFormFragment.kt
  sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt
  sdk/src/main/java/co/omise/android/ui/InstallmentChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/InternetBankingChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/OmiseActivity.kt
  sdk/src/main/java/co/omise/android/ui/OmiseEditText.kt
  sdk/src/main/java/co/omise/android/ui/OmiseFragment.kt
  sdk/src/main/java/co/omise/android/ui/OmiseListFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
  sdk/src/main/java/co/omise/android/ui/SecurityCodeEditText.kt
  sdk/src/main/java/co/omise/android/ui/SecurityCodeTooltipDialogFragment.kt
Labels: v3.0

#110 Api request log
  sdk/src/main/java/co/omise/android/SDKLog.java
  sdk/src/main/java/co/omise/android/SDKLog.kt
  sdk/src/main/java/co/omise/android/api/Configurer.kt
Labels: v3.0

#112 Create capability instance
  app/src/java/java/co/omise/android/example/CheckoutActivity.java
  app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt
  app/src/main/java/co/omise/android/example/PaymentSetting.kt
  app/src/main/java/co/omise/android/example/PaymentSettingFragment.kt
  sdk/src/main/java/co/omise/android/models/Capability.kt
  sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
Labels: enhancement, v3.0

#111 Textual changes 2nd
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference_payment_setting.xml
  sdk/src/main/java/co/omise/android/ui/EContextFormFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
  sdk/src/main/res/values-ja/strings.xml
  sdk/src/main/res/values-th/strings.xml
  sdk/src/main/res/values/strings.xml
Labels: v3.0

#113 Remove certificate pinning
  sdk/src/main/java/co/omise/android/api/Client.kt
  sdk/src/main/java/co/omise/android/api/EndPoint.kt
  sdk/src/test/java/co/omise/android/EndpointTest.java
Labels: v3.0

#114 Capitalize the error messages
  app/src/java/java/co/omise/android/example/CheckoutActivity.java
  app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt
  sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt
  sdk/src/test/java/co/omise/android/extensions/APIErrorExtensionsTest.kt
Labels: enhancement, v3.0

#115 Fix settings
  app/src/main/java/co/omise/android/example/PaymentSetting.kt
  sdk/src/main/java/co/omise/android/models/Capability.kt
Labels: bug, v3.0

#116 User documentation
  README.md
Labels: release, v3.0
