Repository omise/omise-android, pull requests merged in 2023-01, with the labels that each got.

#239 Add Support for Atome
  app/src/main/java/co/omise/android/example/PaymentSetting.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference_payment_setting.xml
  sdk/src/main/java/co/omise/android/models/Billing.kt
  sdk/src/main/java/co/omise/android/models/Items.kt
  sdk/src/main/java/co/omise/android/models/Shipping.kt
  sdk/src/main/java/co/omise/android/models/Source.kt
  sdk/src/main/java/co/omise/android/models/SourceType.kt
  sdk/src/main/java/co/omise/android/ui/AtomeFormFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
  sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
  sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt
  sdk/src/main/res/drawable-hdpi/payment_atome.png
  sdk/src/main/res/drawable-mdpi/payment_atome.png
  sdk/src/main/res/drawable-xhdpi/payment_atome.png
  sdk/src/main/res/drawable-xxhdpi/payment_atome.png
  sdk/src/main/res/drawable-xxxhdpi/payment_atome.png
  sdk/src/main/res/drawable/logo_atome.png
  sdk/src/main/res/layout/fragment_atome_form.xml
  sdk/src/main/res/values-ja/strings.xml
  sdk/src/main/res/values-th/strings.xml
  sdk/src/main/res/values/strings.xml
  sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
Labels: enhancement

#243 [APM2-1427] Don't explicitly throw redirect error
  sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
Labels: bug

#244 4.5.1 Release
  CHANGELOG.md
  build.gradle
Labels: release

#249 v4.6.0 release
  CHANGELOG.md
  build.gradle
Labels: release
